[LC-152] Remove pickle to communicate between peers
icon-project/loopchain pull request #79
Opened 2019-02-12 02:18 UTC by hangaroy

- Remove pickling Block and Transaction instance to communicate between peers

2019-02-18 13:32 UTC, yakkle commented on loopchain/peer/peer_service.py
> +                print(f"sohalee __get_channel_infos peer_id={self.__peer_id}, target={self.__peer_target}, group_id={self.group_id}")
please remove or change to logging.

2019-02-18 13:36 UTC, zsaladin approved these changes

2019-02-18 13:40 UTC, yakkle commented on loopchain/peer/peer_service.py
> +        self.__init_key_by_channel()
something wrong... 😕

2019-02-18 13:40 UTC, yakkle requested changes
need rebase!

2019-02-19 06:42 UTC, yakkle approved these changes

2019-02-20 08:07 UTC, merged